### ISSUE TITLE
[fmbttizen]:Certain characters in the refreshscreenshot() api for tizen provides dump which has hexa values induced inbetween the characters

### ISSUE THREAD

**Issue by madhavpai2000** [01org/fMBT#35]
Hi Antti,

Certain words have hexavalue induced inbtween, them when read from the screenshot using ocr api, this becomes quite difficult for us to use the ocr related api's, Request you to pls handle them if applicable or suggest a workaround if any

for eg: The word "Profile" read from the screenshot and dumped using enableVisualLogs, the html provides the  following value "Pro\xef\xac\x81le"

Thanks,
Madhav

**Comment by askervin** [comment]
Verified to work, closing.
