### ISSUE TITLE
fmbt-editor and fmbt-scripter: ImportError: No module named fmbt_config

### ISSUE THREAD

**Issue by daniel-kun** [01org/fMBT#37]
I just found out about fmbt, downloaded and installed Fedora 21.5 64 Bit Workstation.
I followed the instructions in the Readme.md to the letter.

Everything worked fine, except that now when starting fmbt-editor or fmbt-scripter, I get this error message:

    Traceback (most recent call last):
      File "/usr/local/bin/fmbt-editor", line 66, in <module>
        import fmbt_config
    ImportError: No module named fmbt_config

I searched for fmbt_config and found these files, among a few other fmbt_* files:

    [daniel@fedora-fmbt ~]$ find /usr/local/ -name 'fmbt*config*'
    /usr/local/lib64/python2.7/site-packages/fmbt_config.pyc
    /usr/local/lib64/python2.7/site-packages/fmbt_config.py

There is a `/usr/local/lib/python2.7/site-packages` directory, too (without the 64) which does not contain the fmbt*.py(c) files.

Is it a bug in Fedora, in Python, in fmbt's make install, or is it PEBKAC?

**Comment by askervin** [comment]
Thanks for reporting! I was able to reproduce the problem with the OS you mentioned in a vm. In my setup the problem was solved by adding both ``site-packages`` directories to PYTHONPATH. That is:

```
export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/site-packages:/usr/local/lib64/python2.7/site-packages
```

I've updated README accordingly in the devel branch. Please reopen if the problem persists.

**Comment by daniel-kun** [comment]
Worked, thanks!

**Comment by dondublon** [comment]
Hello. I've got the same problem on Windows. Due to the information above, I looked for the 'fmbt_config' in my python2 site_packages folder, but there is no one. (The installer found this installation while installing.)
I also looked for this file in the library source. Where can I find it?

**Comment by askervin** [comment]
Hi @dondublon! fMBT Windows installer puts `fmbt_config.py` to `C:\Python27\Lib`, which should already be in the default path (`import sys; sys.path`) where Python 2 looks for its libraries on Windows. The latest fMBT Windows installer built by the community can be found from

https://gitlab.com/fmbt/fmbt_ci/-/jobs

(Click [Passed] build_windows_64, then [Browse] Job artifacts on the right.)

Note that the stable fMBT tools from the installer use Python 2. New Python 3 versions of the tools work from the [fMBT docker image](https://github.com/intel/fMBT/blob/devel/Dockerfile), but unfortunately haven't been packaged to OSes yet.

In case you are doing a custom setup on Windows (without the installer), you can use the [fmbt_config template](https://raw.githubusercontent.com/intel/fMBT/devel/utils/fmbt_config.py.in), and fill in the version and build info of your choice.

**Comment by dondublon** [comment]
@askervin Thank you for the answer.
I found the file. It was on exactly C:\Python27\Lib, even though I installed Python2 to another directory. Ok, now I can move further.
