### ISSUE TITLE
failed to install python on tizen device

### ISSUE THREAD

**Issue by tatf** [01org/fMBT#38]
Dear Mr. Antti,
I am trying to use fMBT for UI testing on tizen.It is working fine in tizen emulator but i cannot install python libraries in tizen device.I am using Tizen version 2.3.0.1 , engineering binary.According to your instruction i can root the device,also i can push the libraries.But when i try to install the libraries i got the following errors : 
manjurul@manjurul:~/Downloads$ sdb shell rpm -i /tmp/*.i586.rpm
error: Failed dependencies:
	cpp = 4.5.3-1.2 is needed by cross-armv7l-gcc-4.5.3-1.2.i586
	libgomp = 4.5.3-1.2 is needed by cross-armv7l-gcc-4.5.3-1.2.i586
	eglibc-devel is needed by cross-armv7l-gcc-4.5.3-1.2.i586
	binutils >= 2.19.51.0.14 is needed by cross-armv7l-gcc-4.5.3-1.2.i586
	libc.so.6(GLIBC_2.0) is needed by libpython-2.7.1-1.4.i586
	libc.so.6(GLIBC_2.1) is needed by libpython-2.7.1-1.4.i586
	libc.so.6(GLIBC_2.1.3) is needed by libpython-2.7.1-1.4.i586
	libc.so.6(GLIBC_2.2) is needed by libpython-2.7.1-1.4.i586
	libc.so.6(GLIBC_2.3) is needed by libpython-2.7.1-1.4.i586
	libc.so.6(GLIBC_2.3.4) is needed by libpython-2.7.1-1.4.i586
	libdl.so.2(GLIBC_2.0) is needed by libpython-2.7.1-1.4.i586
	libdl.so.2(GLIBC_2.1) is needed by libpython-2.7.1-1.4.i586
	libm.so.6(GLIBC_2.0) is needed by libpython-2.7.1-1.4.i586
	libm.so.6(GLIBC_2.1) is needed by libpython-2.7.1-1.4.i586
	libpthread.so.0(GLIBC_2.0) is needed by libpython-2.7.1-1.4.i586
	libpthread.so.0(GLIBC_2.1) is needed by libpython-2.7.1-1.4.i586
	libpthread.so.0(GLIBC_2.2) is needed by libpython-2.7.1-1.4.i586
	libutil.so.1(GLIBC_2.0) is needed by libpython-2.7.1-1.4.i586
	libc.so.6(GLIBC_2.0) is needed by python-base-2.7.1-1.4.i586
	libc.so.6(GLIBC_2.1) is needed by python-base-2.7.1-1.4.i586
	libc.so.6(GLIBC_2.1.2) is needed by python-base-2.7.1-1.4.i586
	libc.so.6(GLIBC_2.1.3) is needed by python-base-2.7.1-1.4.i586
	libc.so.6(GLIBC_2.2) is needed by python-base-2.7.1-1.4.i586
	libc.so.6(GLIBC_2.3) is needed by python-base-2.7.1-1.4.i586
	libc.so.6(GLIBC_2.3.2) is needed by python-base-2.7.1-1.4.i586
	libc.so.6(GLIBC_2.3.4) is needed by python-base-2.7.1-1.4.i586
	libcrypt.so.1(GLIBC_2.0) is needed by python-base-2.7.1-1.4.i586
	libm.so.6(GLIBC_2.0) is needed by python-base-2.7.1-1.4.i586
	libm.so.6(GLIBC_2.1) is needed by python-base-2.7.1-1.4.i586
	libnsl.so.1(GLIBC_2.0) is needed by python-base-2.7.1-1.4.i586
	libpthread.so.0(GLIBC_2.0) is needed by python-base-2.7.1-1.4.i586
	libpthread.so.0(GLIBC_2.1) is needed by python-base-2.7.1-1.4.i586
	libpthread.so.0(GLIBC_2.1.1) is needed by python-base-2.7.1-1.4.i586
	libpthread.so.0(GLIBC_2.2) is needed by python-base-2.7.1-1.4.i586

Can you please help me how to solve this problem ?

**Comment by askervin** [comment]
This problem was solved by installing python and libpython rpms from

http://download.tizen.org/releases/2.3/2.3-mobile/tizen-2.3-mobile_20150206.1/repos/target/packages/armv7l/

**Comment by askervin** [comment]
See also the Latest python RPMs issue #18.
