### ISSUE TITLE
fmbt-editor not found

### ISSUE THREAD

**Issue by shadeimi** [01org/fMBT#50]
Following the archlinux guide on the README.txt, using ./configure PYTHON=python2, i got at the end of the process:

21:47 $ fmbt-editor 
Traceback (most recent call last):
  File "/usr/local/bin/fmbt-editor", line 66, in <module>
    import fmbt_config
ImportError: No module named fmbt_config

**Comment by askervin** [comment]
Closing.

**Comment by dondublon** [comment]
Hello. I've got the same problem on Windows. Due to the information above, I looked for the 'fmbt_config' in my python2 site_packages folder, but there is no one. (The installer found this installation while installing.)
I also looked for this file in the library source. Where can I find it?

**Comment by dondublon** [comment]
(The discussion continued here https://github.com/intel/fMBT/issues/37 )
