### ISSUE TITLE
ways to find which action haven't been covered?

### ISSUE THREAD

**Issue by dassio** [01org/fMBT#58]
when generating offline testcases with coverage setting as` coverage(1.0)`, sometimes there is an deadlock, is there a way to find which action haven't been covered?

**Comment by askervin** [comment]
Whether or not it is possible to achieve coverage 1.0 depends on the mode and how coverage is measured.

There is a simple way to stop test generation when the lookahead heuristics cannot see a way to increase coverage. The solution is to add an end condition:
```
pass = lookahead_noprogress
```
Note that if you increase lookahead's search depth, it may be able to achieve greater coverage.

There is no general way to show "what remains uncovered, why coverage does not reach 1.0". In addition to a single action, it may be a huge sequence of actions and/or tags that would need to be covered - and there might be several possible alternatives.

That said, I'll give you some examples on how to see which actions have been covered:

* Visualize how many times each action is executed:
  ``fmbt-stats -f dist:simple -p action_count.svg test.log``
  (A good viewer for the action_count.svg figure is Firefox, for instance.)

* Show how many times each action that has been executed, actually has been executed:
  ``fmbt-log -f '$ax' test.log | sort | uniq -c | sort -n``
  (``sort | uniq -c`` counts how many times each line occurs.)

* Show how many times + 1 all actions have been executed:
  ``( fmbt-log -f '$am' test.log; fmbt-log -f '$ax' test.log ) | sort | uniq -c | sort -n ``
   All actions where you see number 1 have not been executed at all.
  (``$am`` prints all actions in the model, including those that have not been executed in generated test.``$ax`` prints those that have been executed in the log.)
